### ISSUE TITLE
The dropdowns in the List tab should have the number of items required

### ISSUE THREAD

**Issue by DatHaker123** [Joshimello/AL2Lab#4]
![image](https://github.com/Joshimello/AL2Lab/assets/128323804/8dfa3fa3-20e2-430c-9c1d-d3343ee14dae)

Probably as simple as adding 
`<p> {count} <p/>`
to line 41 in src/routes/al2/list.svelte, but there's probably some formatting issues.

**Comment by Joshimello** [comment]
Mmm good idea
![opera_t5xKumD8mD](https://github.com/Joshimello/AL2Lab/assets/74640729/1c361954-d806-414b-922e-7569d25d790d)
Added b858415
