### ISSUE TITLE
What exactly is your plan for the stuff under construction?

### ISSUE THREAD

**Issue by DatHaker123** [Joshimello/AL2Lab#5]
The Flow tab, the 3 dropdowns on the bottom right, and the items/s box

**Comment by Joshimello** [comment]
1. Flow tab should show a tree view of the item production. Here is a rough idea from Factriolab https://factoriolab.github.io/flow?p=encased-plutonium-cell*1&s=sfy&v=9

2. Bottom right not sure yet, might remove if no extra features are requested. Depends if any other users needs any other feature (users currently none :') ).

3. Objective part, should be able to change to what unit of production count, and possible multiple objectives.

**Comment by DatHaker123** [comment]
I'll see if I can do some actual contributions in a week instead of backseat developing. I'm in the middle of my finals rn.

**Comment by Joshimello** [comment]
No worries, just a hobby project :3
